# Generated by Django 5.1.5 on 2025-05-13 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('drawing_image_base64', models.TextField(blank=True, null=True)),
                ('flip_angle', models.FloatField(default=0)),
                ('pages_count', models.IntegerField(default=1)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('is_vertical', models.BooleanField(default=False)),
                ('page', models.IntegerField(default=1)),
                ('type_selection', models.IntegerField(choices=[(1, 'Shaft'), (2, 'Bilateral'), (3, 'Hole')], default=1)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='measuring.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('view_number', models.IntegerField()),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='measuring.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='MeasuredValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measured_values', to='measuring.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='MonittorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('monitor_operation_number', models.IntegerField(blank=True, null=True)),
                ('monitor_order_number', models.IntegerField(blank=True, null=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_informations', to='measuring.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('page_image_base64', models.TextField(blank=True, null=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='measuring.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_operaion_number', models.IntegerField(blank=True, null=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='measuring.drawing')),
                ('measured_values', models.ManyToManyField(related_name='protocols', to='measuring.measuredvalue')),
            ],
        ),
    ]
