# Generated by Django 5.1.5 on 2025-05-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
