# Generated by Django 4.2.5 on 2023-09-23 19:38

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialToBeMachined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undefined', max_length=50)),
                ('colour', models.CharField(default='black', max_length=50)),
                ('group', models.CharField(default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Materials to be machined',
            },
        ),
        migrations.CreateModel(
            name='EndMill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50)),
                ('manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown')),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.CharField(choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss'), ('HSS-E', 'Hss E'), ('HSS-E-PM', 'Hss E Pm'), ('HSS-PM', 'Hss Pm'), ('Cermet', 'Cermet'), ('Ceramic', 'Ceramic'), ('CBN', 'Cbn'), ('PCD', 'Pcd'), ('Diamond', 'Diamond'), ('Carbide tipped', 'Carbide Tipped'), ('Carbide tipped HSS', 'Carbide Tipped Hss'), ('Carbide tipped HSS-E', 'Carbide Tipped Hss E'), ('Carbide tipped HSS-E-PM', 'Carbide Tipped Hss E Pm'), ('Carbide tipped HSS-PM', 'Carbide Tipped Hss Pm'), ('Carbide tipped Cermet', 'Carbide Tipped Cermet'), ('Carbide tipped Ceramic', 'Carbide Tipped Ceramic'), ('Carbide tipped CBN', 'Carbide Tipped Cbn'), ('Carbide tipped PCD', 'Carbide Tipped Pcd'), ('Carbide tipped Diamond', 'Carbide Tipped Diamond'), ('HSS Carbide', 'Hss Carbide'), ('HSS-E Carbide', 'Hss E Carbide'), ('HSS-E-PM Carbide', 'Hss E Pm Carbide'), ('HSS-PM Carbide', 'Hss Pm Carbide'), ('Cermet Carbide', 'Cermet Carbide'), ('Ceramic Carbide', 'Ceramic Carbide'), ('CBN Carbide', 'Cbn Carbide'), ('PCD Carbide', 'Pcd Carbide'), ('Diamond Carbide', 'Diamond Carbide'), ('HSS Carbide tipped', 'Hss Carbide Tipped'), ('HSS-E Carbide tipped', 'Hss E Carbide Tipped'), ('HSS-E-PM Carbide tipped', 'Hss E Pm Carbide Tipped'), ('HSS-PM Carbide tipped', 'Hss Pm Carbide Tipped')], default='Undefined', max_length=50)),
                ('coating', models.CharField(choices=[('Undefined', 'Undefined'), ('Blank', 'Blank'), ('TiN', 'Tin'), ('TiAlN', 'Tialn'), ('AlTiN', 'Altin'), ('TiCN', 'Ticn')], default='Undefined', max_length=50)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('overall_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('neck_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('shank_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('flute_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('usable_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('corner_radius', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('corner_chamfer', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('number_of_flutes', models.PositiveIntegerField(default=1)),
                ('length_category', models.CharField(choices=[('Extra short', 'Extra Short'), ('Short', 'Short'), ('Medium', 'Medium'), ('Medium plus', 'Medium Plus'), ('Long', 'Long'), ('Extra long', 'Extra Long'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('mtbm', models.ForeignKey(default=inventory.models.MaterialToBeMachined.get_default_mtbm, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tools', to='inventory.materialtobemachined')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
