# Generated by Django 4.2.5 on 2023-09-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endmill',
            name='mtbm',
        ),
        migrations.AddField(
            model_name='endmill',
            name='mtbm',
            field=models.ManyToManyField(related_name='tools', to='inventory.materialtobemachined'),
        ),
    ]
