# Generated by Django 4.2.5 on 2023-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_endmill_mtbm_endmill_mtbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endmill',
            name='coating',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('TiN', 'Tin'), ('TiAlN', 'Tialn'), ('AlTiN', 'Altin'), ('TiCN', 'Ticn')], default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='corner_chamfer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='corner_radius',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='diameter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='flute_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='material',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HPC', 'Hpc'), ('HSS', 'Hss')], default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='neck_diameter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='overall_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='shank_diameter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='usable_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
