# Generated by Django 4.2.5 on 2023-09-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_endmill_coating_alter_endmill_corner_chamfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endmill',
            name='ean',
            field=models.CharField(blank=True, default='0000000000000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='material',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HPC', 'Hpc'), ('HSS', 'Hss'), ('VHM', 'Vhm')], default='Undefined', max_length=50),
        ),
    ]
