# Generated by Django 4.2.5 on 2023-09-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_endmill_ean_alter_endmill_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endmill',
            name='neck_diameter',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
