# Generated by Django 4.2.5 on 2023-09-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_endmill_coating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endmill',
            name='coating',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlTiN', 'Altin'), ('AlCrN', 'Alcrn'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='corner_chamfer',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='link',
            field=models.URLField(blank=True, default='Unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='material',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HC', 'Hc'), ('HPC', 'Hpc'), ('HSS', 'Hss'), ('VHM', 'Vhm'), ('HSS-E', 'Hss E'), ('Solid hårdmetall', 'Solid Hårdmetall')], default='Undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='neck_diameter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
