# Generated by Django 4.2.5 on 2023-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_ballmill_material_alter_chamfermill_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballmill',
            options={'ordering': ['-diameter', '-flute_length'], 'verbose_name_plural': 'Ball mills'},
        ),
        migrations.AlterField(
            model_name='ballmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ballmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chamfermill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chamfermill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circularsaw',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circularsaw',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facemill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facemill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lollipopmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lollipopmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='millingbody',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='millingbody',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radiusmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radiusmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='threadmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='threadmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tslotmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tslotmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
    ]
