# Generated by Django 4.2.5 on 2023-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_ballmill_options_alter_ballmill_coating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chamfermill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circularsaw',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facemill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lollipopmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='millingbody',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radiusmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='threadmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tslotmill',
            name='material',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SpotDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True)),
                ('coating', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overall_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('point_angle', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_flutes', models.PositiveIntegerField(default=1)),
                ('flute_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shank_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usable_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mtbm', models.ManyToManyField(related_name='spot_drills', to='inventory.materialtobemachined')),
            ],
            options={
                'ordering': ['-diameter', '-flute_length', '-usable_length'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True)),
                ('coating', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overall_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('point_angle', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_flutes', models.PositiveIntegerField(default=1)),
                ('flute_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shank_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usable_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tolerance', models.CharField(default='Unknown', max_length=50)),
                ('upper_tolerance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lower_tolerance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mtbm', models.ManyToManyField(related_name='reamers', to='inventory.materialtobemachined')),
            ],
            options={
                'ordering': ['-diameter', '-flute_length', '-usable_length'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True)),
                ('coating', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overall_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('point_angle', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_flutes', models.PositiveIntegerField(default=1)),
                ('flute_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shank_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usable_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('length_category', models.CharField(choices=[('3xD', 'Cat 3Xd'), ('5xD', 'Cat 5Xd'), ('7xD', 'Cat 7Xd'), ('8xD', 'Cat 8Xd'), ('10xD', 'Cat 10Xd'), ('12xD', 'Cat 12Xd'), ('20xD', 'Cat 20Xd')], default='Unknown', max_length=50)),
                ('mtbm', models.ManyToManyField(related_name='drills', to='inventory.materialtobemachined')),
            ],
            options={
                'ordering': ['-diameter', '-flute_length', '-usable_length'],
                'abstract': False,
            },
        ),
    ]
