# Generated by Django 4.2.5 on 2023-09-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_ballmill_material_alter_chamfermill_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chamfermill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circularsaw',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facemill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lollipopmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='millingbody',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radiusmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reamer',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reamer',
            name='lower_tolerance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reamer',
            name='upper_tolerance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spotdrill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='threadmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tslotmill',
            name='coating',
            field=models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True),
        ),
    ]
