# Generated by Django 4.2.5 on 2023-09-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_ballmill_coating_alter_chamfermill_coating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True)),
                ('coating', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiN', 'Tin'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overall_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('point_angle', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_flutes', models.PositiveIntegerField(default=1)),
                ('flute_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shank_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usable_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pitch', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('thread', models.CharField(default='Unknown', max_length=20)),
                ('thread_series', models.CharField(default='Unknown', max_length=20)),
                ('thread_class', models.CharField(default='Unknown', max_length=20)),
                ('tap_type', models.CharField(default='Unknown', max_length=20)),
                ('tap_hole_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tap_thread_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mtbm', models.ManyToManyField(related_name='taps', to='inventory.materialtobemachined')),
            ],
            options={
                'ordering': ['-diameter', '-flute_length', '-usable_length'],
                'abstract': False,
            },
        ),
    ]
