# Generated by Django 4.2.5 on 2023-09-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_boringcutter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solidboringcutter',
            name='angle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
