# Generated by Django 4.2.5 on 2023-09-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_solidboringcutter_angle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidGroovingCutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True)),
                ('coating', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('AlTiX', 'Altix'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('HCr', 'Hcr'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('nitr.', 'Nitr'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlCrN', 'Pvd Alcrn'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiCN', 'Ticn'), ('TiN', 'Tin'), ('TiN GS', 'Tin Gs'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True)),
                ('insert_iso_code', models.CharField(default='AAAA 000000', max_length=50)),
                ('cutter_iso_code', models.CharField(default='AAAAA', max_length=50)),
                ('min_bore_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overall_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('functional_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cutting_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_cutting_depth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mtbm', models.ManyToManyField(related_name='solid_grooving_cutters', to='inventory.materialtobemachined')),
            ],
            options={
                'ordering': ['min_bore_diameter', 'cutter_iso_code', '-functional_length'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroovingInternalCutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True)),
                ('coating', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('AlTiX', 'Altix'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('HCr', 'Hcr'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('nitr.', 'Nitr'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlCrN', 'Pvd Alcrn'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiCN', 'Ticn'), ('TiN', 'Tin'), ('TiN GS', 'Tin Gs'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True)),
                ('insert_iso_code', models.CharField(default='AAAA 000000', max_length=50)),
                ('cutter_iso_code', models.CharField(default='AAAAA', max_length=50)),
                ('min_bore_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overall_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('functional_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cutting_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_cutting_depth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mtbm', models.ManyToManyField(related_name='grooving_internal_cutters', to='inventory.materialtobemachined')),
            ],
            options={
                'ordering': ['min_bore_diameter', 'cutter_iso_code', '-functional_length'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroovingExternalCutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('Carbide', 'Carbide'), ('HSS', 'Hss')], default='Undefined', max_length=50, null=True)),
                ('coating', models.CharField(blank=True, choices=[('Undefined', 'Undefined'), ('blank', 'Blank'), ('ånganlöpt', 'Angalopt'), ('AlCrN', 'Alcrn'), ('AlTiN', 'Altin'), ('AlTiX', 'Altix'), ('APX72S', 'Apx72S'), ('Carbo', 'Carbo'), ('CWX500', 'Cwx500'), ('DLC', 'Dlc'), ('DPA72S', 'Dpa72S'), ('DPB72S', 'Dpb72S'), ('DPX14S', 'Dpx14S'), ('DPX22S', 'Dpx22S'), ('DPX72S', 'Dpx72S'), ('DPX74S', 'Dpx74S'), ('F.-nit', 'Fnit'), ('FIRE', 'Fire'), ('HCr', 'Hcr'), ('KS15F', 'Ks15F'), ('nanoFIRE', 'Nanofire'), ('nitr.', 'Nitr'), ('obelagd', 'Obelagd'), ('Perrox', 'Perrox'), ('PVD AlCrN', 'Pvd Alcrn'), ('PVD AlTiN', 'Pvd Altin'), ('Raptor', 'Raptor'), ('Signum', 'Signum'), ('Sirius', 'Sirius'), ('Ti1000', 'Ti1000'), ('Ti1500', 'Ti1500'), ('Ti2000', 'Ti2000'), ('Ti600', 'Ti600'), ('TiAlN', 'Tialn'), ('TiAlN-nanoA', 'Tialn Nanoa'), ('TiAlN-SuperA', 'Tialn Supera'), ('TiCN', 'Ticn'), ('TiN', 'Tin'), ('TiN GS', 'Tin Gs'), ('TiSi', 'Tisi'), ('TiSiN', 'Tisin'), ('Zenit', 'Zenit'), ('ZOX', 'Zox')], default='Undefined', max_length=50, null=True)),
                ('insert_iso_code', models.CharField(default='AAAA 000000', max_length=50)),
                ('cutter_iso_code', models.CharField(default='AAAAA', max_length=50)),
                ('cutting_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_cutting_depth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mtbm', models.ManyToManyField(related_name='grooving_external_cutters', to='inventory.materialtobemachined')),
            ],
            options={
                'ordering': ['cutter_iso_code'],
                'abstract': False,
            },
        ),
    ]
