# Generated by Django 4.2.5 on 2023-09-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_solidgroovingcutter_groovinginternalcutter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tslotmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
    ]
