# Generated by Django 4.2.5 on 2023-09-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_tslotmill_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='boringcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='centerdrill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='chamfermill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='circularsaw',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='drill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='facemill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='groovingexternalcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='groovinginternalcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='lollipopmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='millingbody',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='radiusmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='reamer',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='solidboringcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='solidgroovingcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='spotdrill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='tap',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='u_drill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('guehring', 'Guehring'), ('sandvik', 'Sandvik'), ('hoffmann', 'Hoffmann'), ('ceratizit', 'Ceratizit'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50),
        ),
    ]
