# Generated by Django 4.2.5 on 2023-10-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_turninginsert_options_alter_ballmill_coating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadinsert',
            old_name='Thread_pitch_second',
            new_name='thread_pitch_second',
        ),
    ]
