# Generated by Django 4.2.5 on 2023-10-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_ballmill_coating_alter_boringcutter_coating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groovinginsert',
            options={'ordering': ['width']},
        ),
    ]
