# Generated by Django 4.2.5 on 2023-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_groovinginsert_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.CharField(default='Unknown', max_length=20)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_sealed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['type', 'diameter'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTurning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MeasuringEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precision', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MillingHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(default='AA00-00-000', max_length=50)),
                ('length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('holder_type', models.CharField(default='Unknown', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
