# Generated by Django 4.2.5 on 2023-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_collet_equipmentmilling_equipmentturning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('key_size', models.CharField(default='0', max_length=20)),
            ],
            options={
                'ordering': ['key_size'],
            },
        ),
        migrations.CreateModel(
            name='PostMachining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Post machining items',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Screwdriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('screwdriver_size', models.CharField(default='0', max_length=20)),
            ],
            options={
                'ordering': ['screwdriver_size'],
            },
        ),
        migrations.CreateModel(
            name='Shim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wrench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Wrenches',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipmentmilling',
            options={'ordering': ['code'], 'verbose_name_plural': 'Equipments Milling'},
        ),
        migrations.AlterModelOptions(
            name='equipmentturning',
            options={'ordering': ['code'], 'verbose_name_plural': 'Equipments Turning'},
        ),
    ]
