# Generated by Django 4.2.5 on 2023-10-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_key_postmachining_screwdriver_shim_wrench_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=255)),
                ('tool_type', models.CharField(default='Unknown', max_length=50)),
                ('ean', models.CharField(blank=True, default='0000000000000', max_length=50, unique=True)),
                ('manufacturer', models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy')], default='Unknown', max_length=50)),
                ('description', models.TextField(default='Unknown')),
                ('link', models.URLField(blank=True, default='Unknown', max_length=300)),
                ('picture', models.URLField(blank=True, default='Unknown')),
                ('location', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catalog_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
