# Generated by Django 4.2.5 on 2023-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_boringcutter_options_alter_centerdrill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='ballmill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='boringcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='boringcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='centerdrill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='centerdrill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='chamfermill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='chamfermill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='circularsaw',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='circularsaw',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='collet',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='collet',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='drill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='drill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='drillinginsert',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='drillinginsert',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentmilling',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentmilling',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentturning',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentturning',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='facemill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='facemill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='groovingexternalcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='groovingexternalcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='groovinginsert',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='groovinginsert',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='groovinginternalcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='groovinginternalcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='key',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='key',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='lollipopmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='lollipopmill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='measuringequipment',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='measuringequipment',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='millingbody',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='millingbody',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='millingholder',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='millingholder',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='millinginsert',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='millinginsert',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='postmachining',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='postmachining',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='radiusmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='radiusmill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='reamer',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='reamer',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='screw',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='screw',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='screwdriver',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='screwdriver',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='shim',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='shim',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='solidboringcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='solidboringcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='solidgroovingcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='solidgroovingcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='solidthreadcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='solidthreadcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='spotdrill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='spotdrill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='tap',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='tap',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadexternalcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadexternalcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadinsert',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadinsert',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadinternalcutter',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadinternalcutter',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='threadmill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='tslotmill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='tslotmill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='turninginsert',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='turninginsert',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='u_drill',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='u_drill',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='workholding',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='workholding',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='wrench',
            name='manufacturer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('ceratizit', 'Ceratizit'), ('guehring', 'Guehring'), ('hoffmann', 'Hoffmann'), ('sandvik', 'Sandvik'), ('tungaloy', 'Tungaloy'), ('duemmel', 'Duemmel'), ('phorn', 'Phorn')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='wrench',
            name='tool_type',
            field=models.CharField(choices=[('Cut', 'Cut'), ('Spiral', 'Spiral'), ('Form', 'Form')], default='Unknown', max_length=50),
        ),
    ]
