# Generated by Django 4.2.5 on 2023-11-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_ballmill_tool_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballmill',
            name='tool_type',
            field=models.CharField(choices=[('Mill', 'End Mill'), ('Tap', 'Tap'), ('Ball mill', 'Ball Mill'), ('Face mill', 'Face Mill'), ('Thread mill', 'Thread Mill'), ('Insert turning', 'Insert Turning'), ('Drill', 'Drill'), ('Chamfer mill', 'Chamfer Mill'), ('Collet', 'Collet'), ('General cutter', 'General Cutter'), ('Boring cutter', 'Boring Cutter'), ('Solid boring cutter', 'Solid Boring Cutter'), ('Thread internal cutter', 'Thread Internal Cutter'), ('Solid thread cutter', 'Solid Thread Cutter'), ('Thread external cutter', 'Thread External Cutter'), ('Grooving internal cutter', 'Grooving Internal Cutter'), ('Solid grooving cutter', 'Solid Grooving Cutter'), ('Grooving external cutter', 'Grooving External Cutter'), ('Insert thread', 'Insert Thread'), ('Drill insert', 'Insert Drilling'), ('Shim', 'Shim'), ('Screw', 'Screw'), ('Insert milling', 'Insert Milling'), ('U-Drill', 'U Drill'), ('Key', 'Key'), ('Wrench', 'Wrench'), ('Screwdriver', 'Screwdriver'), ('Milling holder', 'Milling Holder'), ('Insert cutoff', 'Insert Grooving'), ('T-Slot mill', 'Tslot Mill'), ('Circular saw', 'Circular Saw'), ('Equipment turning', 'Equipment Turning'), ('Equipment milling', 'Equipment Milling'), ('Reamer', 'Reamer'), ('Lollipop mill', 'Lollipop Mill'), ('Spot drill', 'Spot Drill'), ('Center drill', 'Center Drill'), ('Milling body', 'Milling Body'), ('Measuring', 'Measuring'), ('Radius mill', 'Radius Mill'), ('Post machining', 'Post Machining')], default='Ball mill', max_length=50),
        ),
        migrations.AlterField(
            model_name='chamfermill',
            name='tool_type',
            field=models.CharField(choices=[('Mill', 'End Mill'), ('Tap', 'Tap'), ('Ball mill', 'Ball Mill'), ('Face mill', 'Face Mill'), ('Thread mill', 'Thread Mill'), ('Insert turning', 'Insert Turning'), ('Drill', 'Drill'), ('Chamfer mill', 'Chamfer Mill'), ('Collet', 'Collet'), ('General cutter', 'General Cutter'), ('Boring cutter', 'Boring Cutter'), ('Solid boring cutter', 'Solid Boring Cutter'), ('Thread internal cutter', 'Thread Internal Cutter'), ('Solid thread cutter', 'Solid Thread Cutter'), ('Thread external cutter', 'Thread External Cutter'), ('Grooving internal cutter', 'Grooving Internal Cutter'), ('Solid grooving cutter', 'Solid Grooving Cutter'), ('Grooving external cutter', 'Grooving External Cutter'), ('Insert thread', 'Insert Thread'), ('Drill insert', 'Insert Drilling'), ('Shim', 'Shim'), ('Screw', 'Screw'), ('Insert milling', 'Insert Milling'), ('U-Drill', 'U Drill'), ('Key', 'Key'), ('Wrench', 'Wrench'), ('Screwdriver', 'Screwdriver'), ('Milling holder', 'Milling Holder'), ('Insert cutoff', 'Insert Grooving'), ('T-Slot mill', 'Tslot Mill'), ('Circular saw', 'Circular Saw'), ('Equipment turning', 'Equipment Turning'), ('Equipment milling', 'Equipment Milling'), ('Reamer', 'Reamer'), ('Lollipop mill', 'Lollipop Mill'), ('Spot drill', 'Spot Drill'), ('Center drill', 'Center Drill'), ('Milling body', 'Milling Body'), ('Measuring', 'Measuring'), ('Radius mill', 'Radius Mill'), ('Post machining', 'Post Machining')], default='Chamfer mill', max_length=50),
        ),
        migrations.AlterField(
            model_name='endmill',
            name='tool_type',
            field=models.CharField(choices=[('Mill', 'End Mill'), ('Tap', 'Tap'), ('Ball mill', 'Ball Mill'), ('Face mill', 'Face Mill'), ('Thread mill', 'Thread Mill'), ('Insert turning', 'Insert Turning'), ('Drill', 'Drill'), ('Chamfer mill', 'Chamfer Mill'), ('Collet', 'Collet'), ('General cutter', 'General Cutter'), ('Boring cutter', 'Boring Cutter'), ('Solid boring cutter', 'Solid Boring Cutter'), ('Thread internal cutter', 'Thread Internal Cutter'), ('Solid thread cutter', 'Solid Thread Cutter'), ('Thread external cutter', 'Thread External Cutter'), ('Grooving internal cutter', 'Grooving Internal Cutter'), ('Solid grooving cutter', 'Solid Grooving Cutter'), ('Grooving external cutter', 'Grooving External Cutter'), ('Insert thread', 'Insert Thread'), ('Drill insert', 'Insert Drilling'), ('Shim', 'Shim'), ('Screw', 'Screw'), ('Insert milling', 'Insert Milling'), ('U-Drill', 'U Drill'), ('Key', 'Key'), ('Wrench', 'Wrench'), ('Screwdriver', 'Screwdriver'), ('Milling holder', 'Milling Holder'), ('Insert cutoff', 'Insert Grooving'), ('T-Slot mill', 'Tslot Mill'), ('Circular saw', 'Circular Saw'), ('Equipment turning', 'Equipment Turning'), ('Equipment milling', 'Equipment Milling'), ('Reamer', 'Reamer'), ('Lollipop mill', 'Lollipop Mill'), ('Spot drill', 'Spot Drill'), ('Center drill', 'Center Drill'), ('Milling body', 'Milling Body'), ('Measuring', 'Measuring'), ('Radius mill', 'Radius Mill'), ('Post machining', 'Post Machining')], default='Mill', max_length=50),
        ),
    ]
