# Generated by Django 4.2.5 on 2023-11-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_boringcutter_tool_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='length_category',
            field=models.CharField(choices=[('3xD', 'Cat 3Xd'), ('5xD', 'Cat 5Xd'), ('7xD', 'Cat 7Xd'), ('8xD', 'Cat 8Xd'), ('10xD', 'Cat 10Xd'), ('12xD', 'Cat 12Xd'), ('15xD', 'Cat 15Xd'), ('20xD', 'Cat 20Xd')], default='Unknown', max_length=50),
        ),
    ]
