# Generated by Django 4.2.5 on 2024-06-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_gauge_measurementtool_measuringpin_threadgauge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadgauge',
            name='gouge_type',
            field=models.CharField(choices=[('Unknown', 'Undefined'), ('Go', 'Go'), ('No-go', 'No Go'), ('Go/No-go', 'Go No Go')], default='Go/No-go', max_length=20),
        ),
    ]
