# Generated by Django 4.2.5 on 2025-08-23 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0048_alter_threadgauge_gouge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inverrntory_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
