# Generated by Django 4.2.5 on 2024-01-03 21:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import monitoring.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('tool_sequence', models.TextField(default='')),
                ('changing_time', models.DurationField(default=datetime.timedelta(0))),
                ('started', models.DateTimeField()),
                ('is_still_running', models.BooleanField(default=True)),
                ('is_setting_cycle', models.BooleanField(default=True)),
                ('is_full_cycle', models.BooleanField(default=False)),
                ('ended', models.DateTimeField(null=True)),
                ('finished_by', models.CharField(default='', max_length=50)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='Unknown poject', max_length=25)),
                ('nc_program', models.CharField(default='T.nc', max_length=25)),
                ('currently_made_quantity', models.IntegerField(default=0)),
                ('required_quantity', models.IntegerField(default=0)),
                ('operation', models.IntegerField(blank=True, null=True)),
                ('operations_total', models.IntegerField(blank=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('part_changing_time', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('cycle_time', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('parts_per_cycle', models.IntegerField(default=1)),
                ('will_end_at', models.DateTimeField(blank=True, null=True)),
                ('full_cycle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='full_cycle', to='monitoring.cycle')),
            ],
            options={
                'ordering': ['started'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('status', models.CharField(default='STOPPED', max_length=20)),
                ('current_tool', models.CharField(default=None, max_length=10, null=True)),
                ('mode', models.CharField(default='AUTOMATIC', max_length=25)),
                ('remain_time', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('this_cycle_duration', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('active_nc_program', models.CharField(default='', max_length=50)),
                ('last_end_cycle_time', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 6, 7, tzinfo=datetime.timezone.utc))),
                ('last_cycle_duration', models.DurationField(default=datetime.timedelta(0))),
                ('current_machine_time', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 6, 7, tzinfo=datetime.timezone.utc))),
                ('last_active_time', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 6, 7, tzinfo=datetime.timezone.utc))),
                ('inactive_time', models.DurationField(default=datetime.timedelta(0))),
                ('last_start', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 6, 7, tzinfo=datetime.timezone.utc))),
                ('last_stop', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 6, 7, tzinfo=datetime.timezone.utc))),
                ('next_offline_file', models.IntegerField(default=0)),
                ('last_offline_file', models.IntegerField(default=0)),
                ('last_offline_date', models.DateField(default=datetime.date(2022, 1, 1))),
                ('m30_counter2', models.IntegerField(default=0)),
                ('m30_counter1', models.IntegerField(default=0)),
                ('tools_maximum', models.IntegerField(default=40)),
                ('mtconnect_port', models.IntegerField(default=8082, validators=[django.core.validators.MaxValueValidator(9000), django.core.validators.MinValueValidator(5000)])),
                ('dprnt_port', models.IntegerField(default=2027, validators=[django.core.validators.MaxValueValidator(9000), django.core.validators.MinValueValidator(1000)])),
                ('network_name', models.CharField(default='Unknown network name', max_length=20)),
                ('active_cycle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='active_cycle', to='monitoring.cycle')),
                ('active_job', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='monitoring.job')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='Machine_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='STOPPED', max_length=20)),
                ('current_tool', models.CharField(default=1, max_length=10, null=True)),
                ('current_M_code', models.CharField(default=0, max_length=10, null=True)),
                ('mode', models.CharField(default='AUTOMATIC', max_length=25)),
                ('active_nc_program', models.CharField(default='O00000', max_length=50)),
                ('current_machine_time', models.DateTimeField(default=datetime.datetime(2022, 1, 1, 6, 7, tzinfo=datetime.timezone.utc))),
                ('this_cycle_duration', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('remain_time', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('last_cycle_duration', models.DurationField(default=datetime.timedelta(0))),
                ('m30_counter2', models.IntegerField(default=0)),
                ('m30_counter1', models.IntegerField(default=0)),
                ('is_current_state', models.BooleanField(blank=None, default=True, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Ofline_XML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_file_number', models.IntegerField(default=0)),
                ('machine', models.ForeignKey(default=monitoring.models.Machine.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='monitoring.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='current_state',
            field=models.ForeignKey(default=monitoring.models.Machine_state.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_machines', to='monitoring.machine_state', verbose_name='current'),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_state',
            field=models.ForeignKey(default=monitoring.models.Machine_state.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='last_machines', to='monitoring.machine_state', verbose_name='last'),
        ),
        migrations.AddField(
            model_name='machine',
            name='previous_cycle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='previous_cycle', to='monitoring.cycle'),
        ),
        migrations.CreateModel(
            name='Day_activity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('starts', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_active', models.DurationField(default=datetime.timedelta(0))),
                ('total_stoped', models.DurationField(default=datetime.timedelta(0))),
                ('machine', models.ForeignKey(default=monitoring.models.Machine.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='monitoring.machine')),
            ],
        ),
        migrations.AddField(
            model_name='cycle',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='monitoring.job'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='machine',
            field=models.ForeignKey(default=monitoring.models.Machine.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='monitoring.machine'),
        ),
    ]
