# Generated by Django 4.2.5 on 2024-01-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='something_changed',
            field=models.BooleanField(default=False),
        ),
    ]
