# Generated by Django 4.2.5 on 2024-01-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_cycle_something_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='something_changed',
            new_name='is_warm_up',
        ),
    ]
