# Generated by Django 4.2.5 on 2024-01-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_rename_something_changed_cycle_is_warm_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_state',
            name='change_status_file_number',
            field=models.IntegerField(default=0),
        ),
    ]
