# Generated by Django 4.2.5 on 2024-01-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_machine_state_change_status_file_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='mode',
            field=models.CharField(default='AUTOMATIC', max_length=25),
        ),
    ]
