# Generated by Django 4.2.5 on 2024-02-02 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_cycle_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='setup_active_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='job',
            name='setup_idle_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='job',
            name='setup_total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
