# Generated by Django 4.2.5 on 2024-02-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_job_setup_active_time_job_setup_idle_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle_archived',
            fields=[
                ('cycle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitoring.cycle')),
            ],
            options={
                'verbose_name': 'Archived Cycle',
                'verbose_name_plural': 'Archived Cycles',
            },
            bases=('monitoring.cycle',),
        ),
    ]
