# Generated by Django 4.2.5 on 2024-02-18 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_cycle_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='machining_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
