# Generated by Django 4.2.5 on 2024-02-18 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_job_machining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='ended',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='mode',
            field=models.CharField(db_index=True, default='AUTOMATIC', max_length=25),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='started',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 1, 1, 6, 7, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['started', 'ended', 'job', 'mode'], name='monitoring__started_f7f6bc_idx'),
        ),
    ]
