# Generated by Django 4.2.5 on 2024-02-18 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import monitoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_cycle_ended_alter_cycle_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archived_cycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('tool_sequence', models.TextField(default='')),
                ('changing_time', models.DurationField(default=datetime.timedelta(0))),
                ('started', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 1, 1, 6, 7, tzinfo=datetime.timezone.utc))),
                ('ended', models.DateTimeField(db_index=True, default=None, null=True)),
                ('finished_by', models.CharField(default='', max_length=50)),
                ('job', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='monitoring.job')),
                ('machine', models.ForeignKey(default=monitoring.models.Machine.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='monitoring.machine')),
            ],
            options={
                'verbose_name': 'Archived Cycle',
                'verbose_name_plural': 'Archived Cycles',
            },
        ),
        migrations.DeleteModel(
            name='Cycle_archived',
        ),
    ]
