# Generated by Django 4.2.5 on 2024-02-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_archived_cycle_delete_cycle_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='was_job_finished',
            field=models.BooleanField(default=False),
        ),
    ]
