# Generated by Django 4.2.5 on 2024-02-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_job_was_job_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_jobs', to='monitoring.machine'),
        ),
        migrations.AlterField(
            model_name='job',
            name='full_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_cycle', to='monitoring.cycle'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='active_job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='active_machine', to='monitoring.job'),
        ),
    ]
