# Generated by Django 4.2.5 on 2024-02-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_job_machine_alter_job_full_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_ready_to_finish',
            field=models.BooleanField(default=False),
        ),
    ]
