# Generated by Django 4.2.5 on 2024-10-05 14:49

from django.db import migrations, models
import django.db.models.deletion
import monitoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_rename_monitoroperation_monitor_operation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor_operation',
            options={'verbose_name': 'Monitor operation', 'verbose_name_plural': 'Monitor operations'},
        ),
        migrations.AddField(
            model_name='monitor_operation',
            name='machine',
            field=models.ForeignKey(default=monitoring.models.Machine.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_operations', to='monitoring.machine'),
        ),
        migrations.AddField(
            model_name='monitor_operation',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
