# Generated by Django 4.2.5 on 2024-10-05 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_alter_monitor_operation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_operation',
            name='planned_finish_date',
            field=models.DateField(default=datetime.date(2022, 1, 1)),
        ),
        migrations.AddField(
            model_name='monitor_operation',
            name='planned_start_date',
            field=models.DateField(default=datetime.date(2022, 1, 1)),
        ),
    ]
