# Generated by Django 4.2.5 on 2024-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_monitor_operation_planned_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_operation',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
