# Generated by Django 4.2.5 on 2024-10-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_monitor_operation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_operation',
            name='drawing_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
