# Generated by Django 4.2.5 on 2024-10-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_monitor_operation_drawing_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor_operation',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
