# Generated by Django 4.2.5 on 2024-10-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_alter_monitor_operation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor_operation',
            name='monitor_operation_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
