# Generated by Django 4.2.5 on 2025-07-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_pushsubscription_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.machine')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.pushsubscription')),
            ],
            options={
                'unique_together': {('machine', 'subscription')},
            },
        ),
    ]
