# Generated by Django 4.2.5 on 2025-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_machinesubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machinesubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='machinesubscription',
            name='event_type',
            field=models.CharField(choices=[('alarm', 'Alarm'), ('cycle_end', 'Cycle End')], default='cycle_end', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='machinesubscription',
            unique_together={('machine', 'subscription', 'event_type')},
        ),
    ]
