# Generated by Django 4.2.5 on 2025-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_alter_machinesubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='user_agetnt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
