# Generated by Django 4.2.5 on 2025-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_pushsubscription_user_agetnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_virtual_machine',
            field=models.BooleanField(default=True),
        ),
    ]
