# Generated by Django 4.2.5 on 2025-10-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_machine_is_virtual_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_operation',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
