# Generated by Django 4.2.5 on 2025-10-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_monitor_operation_is_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_operation',
            name='currently_made_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
