# Generated by Django 4.2.5 on 2025-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_monitor_operation_currently_made_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_operation',
            name='is_setup',
            field=models.BooleanField(default=False),
        ),
    ]
