# Generated by Django 4.2.5 on 2025-12-21 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0029_monitor_operation_is_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_operation',
            name='is_in_pool',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MachineOperationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_manually_overridden', models.BooleanField(default=False)),
                ('manual_override_at', models.DateTimeField(blank=True, null=True)),
                ('current_1_source', models.CharField(choices=[('monitor', 'Monitor'), ('manual', 'Manual')], default='monitor', max_length=10)),
                ('current_operation_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_as_current_1', to='monitoring.monitor_operation')),
                ('current_operation_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_as_current_2', to='monitoring.monitor_operation')),
                ('current_operation_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_as_current_3', to='monitoring.monitor_operation')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_assignment', to='monitoring.machine')),
                ('manual_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monitor_assigned_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.monitor_operation')),
                ('next_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_as_next', to='monitoring.monitor_operation')),
            ],
            options={
                'verbose_name': 'Machine Operation Assignment',
                'verbose_name_plural': 'Machine Operation Assignments',
            },
        ),
    ]
