# Generated by Django 4.2.5 on 2025-12-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_add_machine_operation_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineoperationassignment',
            name='current_1_source',
        ),
        migrations.RemoveField(
            model_name='machineoperationassignment',
            name='current_operation_1',
        ),
        migrations.RemoveField(
            model_name='machineoperationassignment',
            name='current_operation_2',
        ),
        migrations.RemoveField(
            model_name='machineoperationassignment',
            name='current_operation_3',
        ),
        migrations.RemoveField(
            model_name='machineoperationassignment',
            name='is_manually_overridden',
        ),
        migrations.RemoveField(
            model_name='machineoperationassignment',
            name='monitor_assigned_operation',
        ),
        migrations.RemoveField(
            model_name='machineoperationassignment',
            name='monitor_last_updated',
        ),
        migrations.RemoveField(
            model_name='machineoperationassignment',
            name='next_operation',
        ),
        migrations.AddField(
            model_name='machineoperationassignment',
            name='manual_current_operation',
            field=models.ForeignKey(blank=True, help_text="Admin's override for current operation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_current_assignments', to='monitoring.monitor_operation'),
        ),
        migrations.AddField(
            model_name='machineoperationassignment',
            name='manual_next_operation',
            field=models.ForeignKey(blank=True, help_text="Admin's override for next operation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_next_assignments', to='monitoring.monitor_operation'),
        ),
        migrations.AddField(
            model_name='machineoperationassignment',
            name='saved_monitor_current_op_id',
            field=models.CharField(blank=True, default='', help_text='monitor_operation_id at time of manual override (current)', max_length=50),
        ),
        migrations.AddField(
            model_name='machineoperationassignment',
            name='saved_monitor_next_op_id',
            field=models.CharField(blank=True, default='', help_text='monitor_operation_id at time of manual override (next)', max_length=50),
        ),
    ]
