# Generated by Django 4.2.5 on 2025-12-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_simplify_machine_operation_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineoperationassignment',
            name='manual_current_is_idle',
            field=models.BooleanField(default=False, help_text='True if admin marked current slot as idle (no operation)'),
        ),
        migrations.AddField(
            model_name='machineoperationassignment',
            name='manual_next_is_idle',
            field=models.BooleanField(default=False, help_text='True if admin marked next slot as idle (no operation)'),
        ),
    ]
