# Generated by Django 4.2.5 on 2025-12-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0032_add_idle_override_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor_operation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_operations', to='monitoring.machine'),
        ),
    ]
