# Generated by Django 4.2.5 on 2026-01-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0033_allow_null_machine_in_monitor_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_operation',
            name='employee_django_user_ids',
            field=models.JSONField(blank=True, help_text='List of Django User IDs mapped from Monitor Employee IDs', null=True),
        ),
        migrations.AddField(
            model_name='monitor_operation',
            name='employee_ids',
            field=models.JSONField(blank=True, help_text='List of Monitor G5 Employee IDs working on this operation', null=True),
        ),
        migrations.AddField(
            model_name='monitor_operation',
            name='employee_names',
            field=models.JSONField(blank=True, help_text="List of deduplicated display names (e.g., ['Andriy Z', 'Fredrik F'])", null=True),
        ),
    ]
