# Generated by Django 4.2.5 on 2026-10-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0034_monitor_operation_employee_django_user_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('monitor_operation_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('report_number', models.CharField(blank=True, default='', max_length=50)),
                ('part_id', models.CharField(blank=True, default='', max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='monitoring.machine')),
            ],
            options={
                'ordering': ['machine', 'position'],
                'unique_together': {('machine', 'monitor_operation_id')},
            },
        ),
    ]
